schedule_interval: "30 * * * *"
tables:
    - click
    - imp
    - info
    - spot
    - state
    - track
    - int
stage_sql_path: adlogs/load_raw_logs
parent_directory: 'stage_{}_logs_dev'
log_path: 'log/*'
manifest_path_base: "raw-ingester-out/manifests"
manifest_filename: "completed.manifest"
click_manifest_name: click
imp_manifest_name: impression
info_manifest_name: info
int_manifest_name: interaction
spot_manifest_name: spotlight
state_manifest_name: state
track_manifest_name: track
